[profile.default]
src = "contracts/0.8.25"
out = "foundry/out"
libs = ["foundry/lib"]

cache = true
cache_path = "foundry/cache"

solc_version = "0.8.25"
evm_version = "cancun"

optimizer = true
optimizer_runs = 200
via_ir = true

fmt = { int_types = "long" }

remappings = [
  "@openzeppelin/contracts-v5.2/=foundry/lib/openzeppelin-contracts-v5.2/contracts/",
  "@openzeppelin/contracts-v4.4/=foundry/lib/openzeppelin-contracts-v4.4/contracts/",
  "hardhat/=foundry/lib/hardhat/"
]
